# Generated by Django 5.1.1 on 2024-10-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_by',
        ),
    ]
