# Generated by Django 5.1.1 on 2024-10-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Commerce', '0004_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
