# Generated by Django 5.1.1 on 2024-10-07 11:05

import App_Auth.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('otp', models.IntegerField(blank=True, default='', null=True)),
                ('count', models.IntegerField(default=1, help_text='Number of otp sent')),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Model',
                'verbose_name_plural': 'OTPs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', App_Auth.models.LowercaseEmailField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('referral', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lga', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('residential', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gender', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, default='', null=True, upload_to='users')),
                ('referral_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('agree_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
